### ISSUE TITLE
How to disable range requests?

### ISSUE THREAD

**Issue by wintercounter** [joseluisq/static-web-server#104]
~~I'm using the default docker image. I recently moved from Cloudflare proxy to Bunny.net CDN and seems like they don't support range requests, and they are caching incorrectly because of that. I need to disable it completely, but it seems like there is no option for that.~~

UPDATE:
Bunny support said my server is not responding correctly to the range requests. So I wonder what could be the issue here. They are requesting 5MB chunks. I'm using default configuration.

The header they are sending looks like `content-range: bytes */25314`. Is it possible that * is not supported?

UPDATE 2:
I switched to an nginx based container for now, works fine. I was using latest v2 by the way.

**Comment by joseluisq** [comment]
> The header they are sending looks like `content-range: bytes */25314`. Is it possible that * is not supported?

As far as I understood, `content-range: bytes */25314` means a `416 Range Not Satisfiable` status response.
So you have to check how are you requesting byte ranges and if they are valid.
However since you have not shown more info I can only guess.

It would be useful some tracing logs of SWS requests and responses.
