### ISSUE TITLE
Warning: unused configuration manifest key "general.windows-service" or unsuported

### ISSUE THREAD

**Issue by bubnenkoff** [joseluisq/static-web-server#118]
Hi! I decided to try run sws as windows server. I did copy-paste from docs and uncomment windows sections to get it look like:
```
#### Run the web server as a Windows Service
windows-service = true
```
But after starting sws I am getting next warning:
```
static-web-server -w D:/apps/sws/config.toml
Warning: unused configuration manifest key "general.windows-service" or unsuported
Warning: unused configuration manifest key "general.windows-service" or unsuported
PS D:\apps\sws> static-web-server -help
static-web-server 2.9.0
```

**Comment by joseluisq** [comment]
Maybe I didn't specify it in the comments right there but that option is intended to be used in a _Windows Service_ context.
This is not what you are doing with `static-web-server -w D:/apps/sws/config.toml`. 

In other words, you just need to install the Windows Service for SWS via the `static-web-server.exe -w D:/apps/sws/config.toml install` and after only manage it via the Windows Service built-in tools like [sc.exe](https://docs.microsoft.com/en-us/windows/win32/services/configuring-a-service-using-sc) or the [services.msc](https://docs.microsoft.com/en-us/windows/win32/services/services) app.

Just follow the details on the docs to understand it better.
https://sws.joseluisq.net/features/windows-service/

**Comment by joseluisq** [comment]
Also, clarify that the `windows-service = true` via the config file is not needed if you use the `static-web-server.exe -w D:/apps/sws/config.toml install` because the `install` command already does it for you.

However, if you are implementing your own Windows Service and you want to use SWS with it then makes sense to use `windows-service = true` via the config or from CLI.
