### ISSUE TITLE
Can't connect from outside

### ISSUE THREAD

**Issue by bubnenkoff** [joseluisq/static-web-server#119]
Hi! Thanks for your work.

I tried to serve simple static hello world page and get access to it from outside. I tried different ports but I can get access only from `localhost`. If I am trying to access to it with server IP it not opening even from same PC.

It's very look like that sws do not listening 0.0.0.0 for all request. I check ports and seems that it's ok with them.
sws v2.9.0
Windows Server 2022

**Comment by joseluisq** [comment]
I believe that it's because of your firewall settings. So probably you have to define an [_inbound rule_](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-firewall/create-an-inbound-port-rule) to allow inbound network traffic on a specified TCP port of your choice.
Once done if you are running SWS as a Windows Service then don't forget to restart the service to apply the changes.

BTW if you would like to raise any questions then I suggest https://github.com/joseluisq/static-web-server/discussions
