### ISSUE TITLE
Add support for virtual hosting

### ISSUE THREAD

**Issue by kshpytsya** [joseluisq/static-web-server#171]
Please consider adding support for [Virtual Hosting](https://en.wikipedia.org/wiki/Virtual_hosting#Name-based). From configuration point of view it could be as simple as a flag enabling this feature that would imply that the value of the `Host` http header would be appended to `SERVER_ROOT`.

**Comment by joseluisq** [comment]
> this feature that would imply that the value of the `Host` http header would be appended to `SERVER_ROOT`.

It could be but I think that maybe we should give this feature a [TOML config](https://sws.joseluisq.net/configuration/config-file/#toml-file-manifest) place under the `[advanced]` section to let users use custom root dirs per domain instead of just append whatever comes in the `Host` value.

Internally we could keep a list of domains/root dir pairs and try to match the domain value(s) against the incoming `Host` header value.
