### ISSUE TITLE
add webhook support

### ISSUE THREAD

**Issue by Dialga** [joseluisq/static-web-server#263]
**Is your feature request related to a problem? Please describe.**
run shell commands on demand

**Describe the solution you'd like**
Integrate webhooks support in static-web-server

**Describe alternatives you've considered**
https://github.com/adnanh/webhook.

**Additional context**

**Comment by joseluisq** [comment]
There is a related PoC https://github.com/static-web-server/static-web-server/pull/254 ongoing that could satisfy the webhook need.

Feel free to let your thoughts on it.

**Comment by jcgruenhage** [comment]
@Dialga I'd think that that'd be feature creep. Having dedicated software for something just doing file serving and another tool for just having hooks would be better IMO.

If you're looking for a webhook server written in rust, https://github.com/famedly/hookd might fit the bill.

**Comment by joseluisq** [comment]
I was thinking about the idea and I agree with @jcgruenhage that a separate solution should be suitable in this case.
Right now, I do not have a clue how webhooks could be part of SWS so let's see how it goes in the future. 

Additionally, as I said earlier, maybe https://github.com/static-web-server/static-web-server/pull/254 could help here but the problem is that scripting support should even go against the static nature of SWS. That's why the scripting thing will continue in PoC until we decide if makes sense or not. Most likely it will not land in v2 but who knows?

I'm going to close the feature request for now, if there is any news or if you think differently just let me know and we could discuss this further.
