### ISSUE TITLE
CORS not working when Basic Auth enabled

### ISSUE THREAD

**Issue by brianwoo** [joseluisq/static-web-server#336]
### Search for duplicate issues

- [X] I already searched, and this issue is not a duplicate.

### Issue scope

Linux (E.g. Arch Linux, Debian, Alpine, etc)

### Describe the bug

CORS (Access-Control-Allow-Origin) not in response header when basic auth is enabled.

CORS works when running:
./static-web-server --port 8787 --root ./public --cors-allow-origins "*"

CORS does not work when running:
./static-web-server --port 8787 --root ./public --cors-allow-origins "*" --basic-auth 'user:$2y$10$ga2EXn12OAxgxyzRNFy7Se4OvW1fxOAogpFqJZklO0OzBzu5iuqpG'

username: user
password: bbbb

### How to reproduce it

When running with basic auth, I am getting an error:
![image](https://github.com/static-web-server/static-web-server/assets/2199825/464ed3aa-f5e2-4157-998f-9fb8828c433e)

![image](https://github.com/static-web-server/static-web-server/assets/2199825/6d49c4ae-a7b4-41af-9bcb-ca9351835f53)

When without the basic auth, Access-Control-Allow-* returned OK:
![image](https://github.com/static-web-server/static-web-server/assets/2199825/e9f474ab-c9a7-40a6-b4dd-1c0743df0182)

### Expected behavior

Access-Control-Allow-* returned in the response header.

### Complementary information

I have tried this on x86_64 and arm64, both returned the same error.

### Build target

x86_64-unknown-linux-musl

### Environment and specs

- [ ] **static-web-server:** [e.g. v2.28.0]
- [ ] **OS:** [Linux Mint 21.3]
- [ ] **Arch:** [x86_64 (64-bit), ARM64 (64-bit)]
- [ ] **Docker:** [e.g. 26.0.0]
- [ ] **Client:** [Brave 1.64.116, Chromium 123.0.6312.105]

**Comment by joseluisq** [comment]
I would like to clarify some things.

- **Basic Auth:** SWS does not allow `OPTIONS` requests missing the `Authorization` header. Therefore, the server will respond with a `401` status.  
- **CORS:** The SWS `--cors-allow-headers` option should set the `authorization` header (it is not by default). Otherwise, the server will respond with a `403` status.

To summarize (and what we need to do):

- When enabling `--basic-auth`, SWS should allow `OPTIONS` requests without the  `Authorization` header since credentials can be omitted according to the [spec](https://fetch.spec.whatwg.org/#cors-protocol-and-credentials).
-  SWS `--cors-allow-headers` should add also the `authorization` header to the list to work correctly with Basic Auth. 

This is an issue so a fix should come in the next days.

**Comment by joseluisq** [comment]
Ping @ms140569

**Comment by joseluisq** [comment]
Done in #343

Thanks for reporting!
