### ISSUE TITLE
URL Redirects handling falls back to a redirect loop in case of error

### ISSUE THREAD

**Issue by palant** [joseluisq/static-web-server#347]
### Search for duplicate issues

- [X] I already searched, and this issue is not a duplicate.

### Issue scope

Library (crate)

### Describe the bug

While working on #342 I’ve noticed some strange logic in redirect and rewrite handling. In case of errors during calculation of the destination URL, this code will fall back to redirecting to the original URI, effectively resulting in a redirect loop. The underlying error will not be logged. While errors here are unexpected, I don’t think that this is a sensible default.

### How to reproduce it

From what I can tell, this issue is not currently reproducible. Retrieving regex captures should not fail because we run that regex on the same URI earlier. And Aho-Corasick should not fail with the parameters we give it. These are merely assumptions however, neither `regex` nor `aho_corasick` module provide any guarantees that no additional error kinds will be added in future. So I’d rather not rely on these calls never failing.

### Expected behavior

I can see two better ways to handle this. The most correct solution would be logging the error and producing a 500 response. It might be an overkill here however.

The simpler solution would be falling back to the unmodified destination URL, without resolving the captures. Since the potential error is likely somehow related to the captures, skipping this step seems acceptable.

Given that someone might need to recognize and fix an issue, I’d still prefer the former solution.

### Build target

Built from source (specify below)

### Environment and specs

- [x] **static-web-server:** current development branch (https://github.com/static-web-server/static-web-server/commit/1c4fad200997903d31ce83e50a29b0e8aea508d0)

### Additional context

I intend to fix this while I’m messing with this code for #342 anyway.

**Comment by joseluisq** [comment]
Good catch! I agree with not relying on the positive case only in general. 

> I can see two better ways to handle this. The most correct solution would be logging the error and producing a 500 response. It might be an overkill here however.

I find this solution acceptable, except for responding with 500.
If you asked me, I would vote for logging the error and keeping the redirection loop because first, the user will know what is the problem (error log) and the actual behavior (loop). Of course, assuming that this redirection loop _is_ a valid behavior for leaving it intact.

In this regard, I recall situations when one could misconfigure Nginx directives for example when handling requests and redirects and then getting a redirection loop when testing or the _Too Many Redirects_ in the browser.

Anyway, this will need some discussion to decide what is appropriate. Feel free to share your thoughts.

**Comment by palant** [comment]
> I find this solution acceptable, except for responding with 500.

Why not? We clearly have an error here that we did not expect and don’t know how to deal with. Returning 500 seems the appropriate course of action.

One can certainly misconfigure nginx to produce a redirect loop, just as one can misconfigure the redirects functionality (just set identical source and destination). But I don’t think that letting the browser produce 10 server requests before it gives up (or how many requests will it be?) is an appropriate way of indicating an error.

**Comment by joseluisq** [comment]
> One can certainly misconfigure nginx to produce a redirect loop, just as one can misconfigure the redirects functionality (just set identical source and destination). But I don’t think that letting the browser produce 10 server requests before it gives up (or how many requests will it be?) is an appropriate way of indicating an error.

Sure, a 500 response is the way to go if we know that the code has reached an error case. For example, malformed replacements, invalid URLs, paths, etc.

I'm not against the solution though. I just wanted to find the association between a 500 status code and setting identical source and destination URL redirects (which is technically valid).

Anyway, if the goal is to detect and prevent infinite redirection loops for users then logging the error and returning 500 responses seems fine.

Perhaps I was too aligned with the user's use case behavior itself rather than the server's correctness.

**Comment by palant** [comment]
#348 now fixes half of this issue. Let me know what you think.

> Anyway, if the goal is to detect and prevent infinite redirection loops for users then logging the error and returning 500 responses seems fine.

I wouldn’t go quite as far as claiming that preventing infinite redirection loops is a goal. If they misconfigure SWS by specifying identical source and destination, it’s IMHO ok to indicate that by allowing the loop. But it’s not the same thing as a configuration accidentally triggering an error.

**Comment by joseluisq** [comment]
Alright, let's go then with the approach that you described, which basically means logging the error and producing a 500.

**Comment by palant** [comment]
> Alright, let's go then with the approach that you described, which basically means logging the error and producing a 500.

Actually, that’s done already – in #348 and #353.
