### ISSUE TITLE
Running benchmarks once per year is not sufficient

### ISSUE THREAD

**Issue by palant** [joseluisq/static-web-server#352]
### Search for duplicate feature request

- [X] I already searched, and this feature request or improvement is not a duplicate.

### Feature scope

Build target (release binary)

### Feature request related to a problem

As I’m implementing changes right now, I don’t really like guessing about performance impact. I’d like to see it if my changes cause a performance regression.

### Describe the solution you'd like

I want to try running benchmarks via a Github Action, so that we have some data for each change. Yes, the action runner isn’t a platform with reliable hardware characteristics. However, if we also measure lighttpd/nginx/apache for comparison, this might be good enough to detect at least significant performance degradations.

### Describe alternatives you've considered

It would of course be possible to get a cloud server with known hardware parameters for this task, it should produce more reliable results. But that’s probably an overkill for now.

### Build target

All targets

**Comment by joseluisq** [comment]
Yes, there is also people wanting to see updates about this like https://github.com/static-web-server/benchmarks/issues/3.

Regardless, I agree that in order to improve performance and prevent regressions, we need some continuous benchmarking solution.

For example, we could set up / refactor our CI workflows and run our microbenchmarks continuously. Another alternative is a  cloud solutions like https://bencher.dev/ that are free for public repositories or any other.

But the CI itself has to be improved for example to run the microbenchmarks, use valgrind to check for memory leaks (e.g.  https://github.com/tokio-rs/tokio/blob/master/.github/workflows/ci.yml#L273), etc.

And now that the code is getting more visibility on it's own place (modules). We could better optimize and incorporate benchmarks via criterion progressively.
I do not expect to benchmark every single peace of code of course but the hot parts or where makes sense.
BTW, there here are a few for future reference.

In the other hand, the benchmark repo is an HTTP load testing benchmark comparison that could complement the whole picture but can be also automated.

Definitely, there is room for improvement in the performance front. Feel free to propose something in a draft.

**Comment by joseluisq** [comment]
@palant now that https://github.com/static-web-server/static-web-server/pull/355 can we close this?

**Comment by gaby** [comment]
@joseluisq @palant Any chance of adding Caddy to the benchmarks list?

**Comment by palant** [comment]
> @joseluisq @palant Any chance of adding Caddy to the benchmarks list?

Sure, I’ve created #379.

Caddy performance results are surprising. It ranks really well when compressing large files – but it doesn’t compress well. Even when I set compression level to 9 I get 22 KiB instead of the expected 18 KiB. In all other benchmarks it ranks consistently worse than SWS, and it consistently produces nasty outliers where latency is much higher than usual. Directory listings in particular are extremely slow (also quite a bit more complex than what other servers show).

**Comment by palant** [comment]
Ah, forgot to restart after config change apparently, makes sense now. With compression level 9 I do get the expected 18 KiB. But the default compression level seems to be 1, same as nginx. While I could reconfigure them, using a lower compression level in SWS is actually a better idea.
