### ISSUE TITLE
Rename default branch into main

### ISSUE THREAD

**Issue by palant** [joseluisq/static-web-server#386]
### Search for duplicate feature request

- [X] I already searched, and this feature request or improvement is not a duplicate.

### Feature scope

Completely new feature

### Feature request related to a problem

The Git default branch was [renamed to `main` several years ago](https://www.theserverside.com/feature/Why-GitHub-renamed-its-master-branch-to-main). This repository is older and still uses the legacy name. It should be renamed, for consistency if nothing else.

### Describe the solution you'd like

Renaming the branch is [easy enough](https://github.com/github/renaming?tab=readme-ov-file#renaming-existing-branches). Existing links should redirect automatically, so if everything will be affected then the GitHub workflows that will be limited to the wrong branch. But I can create a PR updating everything.

### Describe alternatives you've considered

-

### Build target

All targets

**Comment by joseluisq** [comment]
> The Git default branch was [renamed to `main` several years ago](https://www.theserverside.com/feature/Why-GitHub-renamed-its-master-branch-to-main). This repository is older and still uses the legacy name. It should be renamed, for consistency if nothing else.

I'm aware about since years ago when the "debate" started with the slavery argument that is in my opinion a weak argument.
Unfortunately, I didn't and still don't see a coherent rational about why projects should rename their branches just because someone thought that the word master "alludes" to slavery.

For example, several projects included Rust, Kernel, etc have not renamed their branches and probably they won't.

> Renaming the branch is easy enough. Existing links should redirect automatically, so if everything will be affected then the GitHub workflows that will be limited to the wrong branch. But I can create a PR updating everything.

I reaffirm my position to keep things like they are now.
So no need to do extra work for this.

--

However, if there are other strong reasons (e.g. technical) why we have to do the change I'm open to discuss it.

I hope you understand.

**Comment by palant** [comment]
I feel strongly that this is neither mine nor your place to decide whether these arguments are weak, we aren’t the ones affected. If people feel offended, it’s really simple to accommodate them. I’d gladly do the “extra work.”
