### ISSUE TITLE
MBP M1 12.2 - server process not closing when terminated since v 2.2 0

### ISSUE THREAD

**Issue by Blatman** [joseluisq/static-web-server#83]
M1 12.2 Monterey  - occurs with both Intel and Arm binaries (standard release downloads)

Downloaded v2.5.0, unzipped and double clicked to start server. Once through all the verification stuff the sws process appears in Activity Monitor. Wait a little while then close terminal window. No client sessions using server at all.
v2.1.0 - process closes immediately.
v2.2.0 - process stays open but appears as null in info.
v2.5.0 - process stays open but appears as null in info.

Tried the intel binary on 10.13 High Sierra but wouldn't launch - I think the release binaries are built for later OS versions only.

Sample screenshots -

v2.1.0 terminated -
<img width="655" alt="sws-v210-terminated" src="https://user-images.githubusercontent.com/11089335/154359154-d2943086-d703-4b0f-9574-4ebf801268bf.png">

v2.2.0 started -
<img width="578" alt="sws-v220-started" src="https://user-images.githubusercontent.com/11089335/154359299-121dd80d-c689-471b-83d1-aad2fa9cd96a.png">

v2.2.0 terminated -
<img width="621" alt="sws-v220-terminated" src="https://user-images.githubusercontent.com/11089335/154359317-ba60f3e5-96b7-4bf7-bf45-7e13f8aa7794.png">

v2.5.0 terminated -  server process still there even after max. grace period of 4.5 mins
<img width="705" alt="sws-v250-terminated for 10 mins" src="https://user-images.githubusercontent.com/11089335/154359334-8fb2f741-1275-4f85-a347-078407d1339c.png">

**Comment by joseluisq** [comment]
It would be great if you can enable `trace` logs and share it here.

**Comment by joseluisq** [comment]
This is not something related to SWS but how your terminal app behaves.

In other words, usually to terminate a process you have to signal it or just exit the current shell session (Ctrl + C).
**But** if you just close the tab of your app or the app itself, AFAICT your terminal app is not sending any signal to SWS to terminate. Therefore it continues running even.

So just signalling properly to SWS does what is expected to do. E.g `kill -s TERM <PID>`

**Comment by Blatman** [comment]
mmm - weird just tried again and when binary is double-clicked it executes in a standard zsh shell window. 
If the window is closed with the close button the process does not close since v2.2.0
If the window is closed with the ^c the process closes OK on all versions
- so close button on terminal window not supported since v 2.2.0

**Comment by joseluisq** [comment]
> If the window is closed with the close button the process does not close since v2.2.0

The only difference prior to v2.2.0 is that we introduced the ability of graceful shutdown the server. As you saw, the server can react to a set of **standard** termination signals and shutdown properly.

> * so close button on terminal window not supported since v 2.2.0

I have repeated your test on one Mac and it is gone after close the tab on [v2.1.0](https://github.com/joseluisq/static-web-server/releases/tag/v2.1.0) but it is not on [v2.2.0](https://github.com/joseluisq/static-web-server/releases/tag/v2.2.0).
This is because v2.1.0 **only** terminates the server when you press `ctrl+c` from your terminal or if you kill the process on demand.

So the tab thing is maybe because of the graceful shutdown feature (v2.2.0 onward).

However I still don't see it as an issue that's why I can not guarantee that I will give this some priority.
Because first it needs more debugging (maybe you could help me here).
And second, I don't know what signal is your terminal sending (looks like is not sending something) or even _**I don't know how Mac decides to terminate the process (v2.1.0)**_ just closing the tab.
So this is something out of SWS scope at this point.

But if you can help me providing more insights would be great.

--

Finally, since SWS (v2.2.0+) is not able to catch any signal when your close your app's tab (I still see this as your App-matter thing rather than SWS).
I suggest to either use a proper `ctrl+c` if you want to terminate the server or put your server to run as a background process via [launchd](https://en.wikipedia.org/wiki/Launchd) and manage it as a service so you can start it or stop it as you need.

**Comment by joseluisq** [comment]
Last thing maybe you want to adjust your Terminal app settings in order to do what you need when closing a tab.

**Comment by Blatman** [comment]
Yea thanks Jose - I'll be trying in a more normal scenario using child process which will probably work OK but the double-click on the binary was just a quick way of determining whether it would run and I found the anomaly. If I happen to find anymore about the close signal from the terminal window button I'll let you know.
Cheers.
