### ISSUE TITLE
Speed comparison

### ISSUE THREAD

**Issue by firstdorsal** [joseluisq/static-web-server#90]
This project looks awesome!

I just wondered how fast it is compared to nginx or similar servers?

**Comment by joseluisq** [comment]
Definitely Nginx should beat SWS with ease.

I did a very shallow 1min test via `wrk` on my Linux laptop Core i7 2.5Ghz, 8GB RAM

**SWS**

Using default settings

```sh
static-web-server -V
# static-web-server 2.6.0
static-web-server -d public/
```

```sh
wrk --latency -t4 -c100 -d1m http://localhost
# Running 1m test @ http://localhost
#   4 threads and 100 connections
#   Thread Stats   Avg      Stdev     Max   +/- Stdev
#     Latency     4.93ms    1.01ms  23.03ms   73.32%
#     Req/Sec     5.09k   222.25     5.41k    87.62%
#   Latency Distribution
#      50%    4.94ms
#      75%    5.48ms
#      90%    6.11ms
#      99%    7.53ms
#   1215900 requests in 1.00m, 830.26MB read
# Requests/sec:  20262.09
# Transfer/sec:     13.84MB
```

Requests/sec:  `20262.09`
CPU used: `56%` approx.
RAM used: `5,292K` (`5.2MiB`)

**Nignx**

Using a fresh Nginx installation with its default settings as well
```sh
nginx -v
# nginx version: nginx/1.20.2
```

```sh
wrk --latency -t4 -c100 -d1m http://localhost
# Running 1m test @ http://localhost
#   4 threads and 100 connections
#   Thread Stats   Avg      Stdev     Max   +/- Stdev
#     Latency     4.53ms    3.53ms 224.89ms   99.44%
#     Req/Sec     5.71k   550.58     7.73k    67.38%
#   Latency Distribution
#      50%    4.28ms
#      75%    4.86ms
#      90%    5.14ms
#      99%    6.09ms
#   1363609 requests in 1.00m, 0.95GB read
# Requests/sec:  22708.28
# Transfer/sec:     16.16MB
```

Requests/sec:  `22708.28`
CPU used: `20%`
RAM used: `1,672K` (`1.6MiB`)

---

The tests are generic and should only give a relative idea about "the comparison".
and yes, the **battle-tested** Nginx beats SWS, consumes less resources and in a constant way rather than SWS.

However SWS is a young project in comparison of Nginx and its maintainer (me) has a long way to go in order to contribute with performance optimizations. But I keep "optimistic".

So if you are interested on performance and you would like to help. Don't hesitate to get involved.

**Comment by firstdorsal** [comment]
Thank you very much for this estimation!
This actually does look pretty good for such a young project compared to this massive old project.
